### ISSUE TITLE
Search by translation in Cyrillic does not work because translation is saved as unicode characters

### ISSUE THREAD

**Issue by tuseto** [lara-zeus/translatable#19]
` "laravel/framework": "^11.0",`
 `"kenepa/translation-manager": "^4.0"`, (using zeus fork)
Reproduction is simple.
Use some Cyrillic language, in my case Bulgarian.
Save
In the database there is the word but encoded like \u041c\u0418\...
As of my research this is because laravel by default uses on `$model->update` `json_encode` without flag so the conversion results in unicode characters.
Using filament-spatie-translatable (which obviously uses spatie-translatable) there is no such a problem. Their package does not use `Database/QueryBuilder` save/update, don't remember which were the methods, so they do it some other way.

Is there some simple solution to this case ?

**Comment by atmonshi** [comment]
sorry for the delay.

I am not sure about: **kenepa/translation-manager**
also my fork don't have and handling like `json_encode` etc. because I depend completely on `spatie-translatable` for the saving.

maybe check the `translation-manager` plugin if they have any json decoding stuff?

will close it for now, feel free to reopen with more details :)
